version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./sharing_pictures_webapp:/app
      - ./sharing_pictures_webapp:/db.sqlite3
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000