version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    image: python:3.11.6
    volumes:
      - ./sharing_pictures_webapp:/db.sqlite3
    ports:
      - "3000:3000"
    command: python manage.py runserver 127.0.0.1:8080/

  frontend:
    container_name: frontend
    build: ./frontend
    image: node:18-alpine
    ports:
      - "8000:8000"
    command: npm run dev