from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'), #TODO logout
    path('load_pictures/', views.load_pictures, name='load_more_pictures'),
    path('upload/', views.upload_picture, name='upload_picture'),
    path('search/', views.search, name='search'),
    path('search_pictures/', views.search_pictures,name='search_pictures'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('likes/', views.like, name='likes'),
    path('get_logged_in_user/', views.get_logged_in_user, name='get_logged_in_user'),
    path('get_is_liked/', views.get_is_liked, name='get_is_liked'),
    path('follow/', views.follow, name='follow'),
    path('get_is_user_following/', views.get_is_user_following, name='get_is_user_following'),
    path('getOwnerPost/', views.getOwnerPost, name='getOwnerPost'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('load_liked_pictures/', views.load_liked_pictures, name='load_liked_pictures'),
    path('get_avatar/', views.get_avatar, name='get_avatar'),
    path('load_following_pictures/', views.load_following_pictures, name='load_following_pictures'),
    path('upload_comment/', views.upload_comment, name='upload_comment'),
    path('getCommentsOfPost/', views.getCommentsOfPost, name='getCommentsOfPost'),
    path('deleteCommentPost/', views.delete_comment, name="deleteCommentPost"),
    path('load_liked_pictures/', views.load_liked_pictures, name='load_liked_pictures'),
    path('report_post/', views.report_picture, name='report_post'),
    path('moderation_panel/', views.moderation_panel, name='moderation_panel'),
    path('delete_post/<str:post_id>/', views.delete_post, name='delete_post'),
    path('delete_rep/<str:post_id>/', views.delete_report, name='delete_report'),
    path('report_user/', views.report_user, name='report_user'),
    path('delete_user/<str:user_id>/', views.delete_user, name='delete_user'),
    path('delete_rep_user/<str:user_id>/', views.delete_user_report, name='delete_user_report'),
    ]
