# Generated by Django 4.2.6 on 2023-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(related_name='user_posts', to='main_app.post'),
        ),
    ]
