# Generated by Django 4.2.6 on 2023-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_options'),
        ('main_app', '0003_rename_user_customuser'),
    ]

    operations = [
    ]
