# Generated by Django 4.2.6 on 2023-11-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_created_at'),
        ('main_app', '0006_alter_post_created_at'),
    ]

    operations = [
    ]
