# Generated by Django 4.2.6 on 2023-12-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
