# Generated by Django 4.2.6 on 2023-12-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_userreports'),
        ('main_app', '0010_reports'),
    ]

    operations = [
    ]
