name: Create PR to Main

on:
  workflow_run:
    workflows: ["Run Tests on Dev"]
    types:
      - completed
      
permissions:
  contents: write
  
jobs:

  create_pr_to_main:
  
    runs-on: ubuntu-latest

    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2

    - name: Config git name
      run: git config --global user.name "Francesc"
    - name: Config git email
      run: git config --global user.email "fparcerisasv@gmail.com"
    - name: Create PR to main
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.WORKFLOW_CI }}
        pr_title: "Automated main PR"
        pr_body: "This is an automated pull request created after tests passed successfully."
        pr_label: "automated-pr"
