name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Create migrations
      run: python manage.py makemigrations
    - name: Apply migrations
      run: python manage.py migrate
    - name: Build Docker image
      run: docker build -t ub-es-2023-b3 .
    - name: Tag Docker image
      run: docker tag ub-es-2023-b3 ${{ secrets.DOCKER_HUB_USERNAME }}/ub-es-2023-b3:3.0
    - name: Docker Hub login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker image
      run: docker push quimlr/ub-es-2023-b3:3.0
