name: Build and Deploy Docker Image on Docker Hub [DEPRACATED]

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:

  build-and-deploy-docker-hub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Create migrations
      run: python manage.py makemigrations
    - name: Apply migrations
      run: python manage.py migrate
    - name: Run build frontend
      run: |
        cd frontend
        npm run build
        cd ..
    - name: Docker Hub login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ub-es-2023-b3:3.0 .
    - name: Tag Docker image
      run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/ub-es-2023-b3:3.0 ${{ secrets.DOCKER_HUB_USERNAME }}/ub-es-2023-b3:3.0
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ub-es-2023-b3:3.0
