name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ub-es-2023-b3 .
    - name: Tag the Docker image
      run: docker tag ub-es-2023-b3 quimlr/ub-es-2023-b3:3.0
    - name: Push the Docker image to DockerHub
      run: docker push quimlr/ub-es-2023-b3:3.0
