name: Build and deploy container app to Azure Web App - sharing-pictures

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Create migrations
      run: python manage.py makemigrations

    - name: Apply migrations
      run: python manage.py migrate

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8ad7f13dfd704afc89f3ffa4cefffb33 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_67e707994b4144a78bfeea7cdb54a97b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8ad7f13dfd704afc89f3ffa4cefffb33 }}/ub-es-2023-b3:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sharing-pictures'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd7248c58de84cbeb6c9c3880f41ae10 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8ad7f13dfd704afc89f3ffa4cefffb33 }}/ub-es-2023-b3:${{ github.sha }}'
