name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
  
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_316964246a3e4586a4e4e5d470a53671 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e382e98e205545c4a2c3a53cc10c027c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: quimlr/ub-es-2023-b3:${{ github.sha }}
        file: ./Dockerfile
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  deploy:
  
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sharing-pictures'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7439146f06544acbaac34cf2058b4e60 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_316964246a3e4586a4e4e5d470a53671 }}/quimlr/ub-es-2023-b3:${{ github.sha }}'
