# NOT WORKING ATM, DO NOT DELETE OR MODIFY

name: Build and deploy container app to Azure Web App - sharing-pictures

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_94fa00d29a6e456a93aab7d04dd0ccba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a79f13a9fe4d425f8781a53efb9aa915 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_94fa00d29a6e456a93aab7d04dd0ccba }}/quimlr/ub-es-2023-b3:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sharing-pictures'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bb30f943bae842e88fcb71f3c8cf0511 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_94fa00d29a6e456a93aab7d04dd0ccba }}/quimlr/ub-es-2023-b3:${{ github.sha }}'
