name: Django Tests with Coverage

on:
  pull_request:
    branches:
      - dev2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update pip
      run: pip install --upgrade pip
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Checkout pull request branch
      run: git checkout -B ${{ github.event.pull_request.head.ref }}

    - name: Create migrations
      run: python manage.py makemigrations
      
    - name: Apply migrations
      run: python manage.py migrate
      
    - name: Run build frontend
      run: |
        cd frontend
        npm run build
        cd ..

    - name: Install coverage
      run: pip install coverage

    - name: Run Django tests with coverage
      run: |
        coverage run manage.py test

    - name: Display coverage report
      run: coverage report

    - name: Generate HTML coverage report
      run: coverage html

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov
